# version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: cmd/server/Dockerfile
    volumes:
      - ./data:/data
    ports:
      - "8080:8080"
    environment:
      - DB_PATH=/data/trades.db

  worker:
    build:
      context: .
      dockerfile: cmd/worker/Dockerfile
    volumes:
      - ./data:/data
    depends_on:
      - server
    environment:
      - DB_PATH=/data/trades.db